# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-22 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0002_auto_20170422_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='additional_notes',
            field=models.TextField(blank=True, help_text="Anything else you'd like the program committee to know when making their selection: your past experience, etc. This is not made public. Edit using <a href='http://daringfireball.net/projects/markdown/basics' target='_blank'>Markdown</a>.", verbose_name='Addtional Notes'),
        ),
    ]
